apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bankchase-ingress
  namespace: bankchase
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - bankchase.example.com
    - api.bankchase.example.com
    secretName: bankchase-tls
  
  rules:
  - host: bankchase.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bankchase-frontend
            port:
              number: 80
  
  - host: api.bankchase.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bankchase-backend
            port:
              number: 80
