apiVersion: v1
kind: ServiceAccount
metadata:
  name: bankchase-backend
  namespace: bankchase

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bankchase-frontend
  namespace: bankchase

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bankchase-reader
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bankchase-backend-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bankchase-reader
subjects:
- kind: ServiceAccount
  name: bankchase-backend
  namespace: bankchase

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bankchase-frontend-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bankchase-reader
subjects:
- kind: ServiceAccount
  name: bankchase-frontend
  namespace: bankchase
